### ISSUE TITLE
Abandon this package

### ISSUE THREAD

**Issue by gmsantos** [leroy-merlin-br/larasniffer#9]
Nowadays PHPSniffer `phpcs.xml` configuration can:

- Configure colored outputs
- Set codestyle rules
- Configurable include and exclude paths patterns

Since this package does not add anything new to default code sniffer and does not support Laravel 5 too, I think it is prudent to abandon this package and document how to do the same using only PHP Sniffer.

Any toughs? @Zizaco , @GuilhermeGuitte , @ravanscafi , @rplansky ?

**Comment by diego3** [comment]
Thank you!
